### PR TITLE
Convert to kootlin

### PR DESCRIPTION
**Pull request by SollyW**
convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin convert to kootlin

### CODE REVIEW

**Comment by MsRandom** [comment]
based

**Review by MsRandom — COMMENTED** [review]
You should probably access properties via delegates, ie `val propertyName: String by project`, as it's cleaner than doing `properties["propertyName"]`.

**Comment by SollyW** [comment]
Hmm, even when they're only used once?

**Comment by MsRandom** [comment]
Yeah, I think declaring what's going to be used just looks better

**Comment by SollyW** [comment]
I can't use delegates (to my knowledge - there might be a feature I'm unaware of) since the property names contain underscores, which don't follow naming conventions for kotlin values. I could do `val propertyName = properties["property_name"].toString()`, though

**Comment by MsRandom** [comment]
You could rename the properties to be camel case, that's what I usually do.

Also, declaring it as a variable but accessing it from `properties` is worse imo since you need to type the name twice

**Comment by SollyW** [comment]
Perhaps. I'll wait for someone else's opinion on it before I go with it

**Review by Azzyypaaras — APPROVED** [review]
I would fuck it, probably rim it.

**Comment by gudenau** [comment]
Kotlin is evil.

**Comment by MsRandom** [comment]
> Kotlin is evil.

@gudenau is evil.

**Comment by Jack-Papel** [comment]
@gudenau Eviller than groovy? 🥴

**Comment by MsRandom** [comment]
Also the alternative in this case is Groovy which I'm sure we can all agree is worse

**Comment by gudenau** [comment]
We are currently using groovy, why change it when it works and they are both bad?

**Comment by MsRandom** [comment]
Kotlin build scripts are far better imo and they are way less prone to breaking with changes, due to their statically typed and compiled nature

**Comment by SollyW** [comment]
It might be nice to extract plugin versions to the properties file. In particular, crowdin includes the minecraft version in its version

**Comment by MsRandom** [comment]
I think the delegates look a lot better, although shouldn't they be localized to their scope, rather than being global?

**Comment by SollyW** [comment]
Perhaps. On the other hand, having them all in one place is nice

**Pull request closed without merging**
