### PR TITLE
Better golden oak leaves, more unique.

### PR DESCRIPTION
**Pull request by ketufaispikinut**
I made golden oak leaves more unique, at least i think so.

### CODE REVIEW

**Comment by CDAGaming** [comment]
CC'd those related to texturing to approve this 👍

**Comment by ketufaispikinut** [comment]
> CC'd those related to texturing to approve this 👍

**Comment by ketufaispikinut** [comment]
what did i just do

**Comment by CDAGaming** [comment]
You closed the pr, so I re-opened it

**Comment by CDAGaming** [comment]
@ketufaispikinut Please make seperate branches for different PRs.

**Review by MBatt1 — COMMENTED** [review]
Personally I don't think these are an improvement and don't really need a change, but in any case your texture has a slight tiling issue with a large gap in the texture, and a stray transparent pixel. 
The shape also is a bit funky and doesn't really look like leaves to me, at least not like the particles that fall from the tree. Feedback of the current texture is welcome (its not perfect), feel free to message in the discord channel, but I don't believe these leaves are improving the current texture.
image
Leaf comparison with oak leaves on the bottom row.

**Comment by MBatt1** [comment]
I already mentioned this on the other PR, but make separate branches for any PRs you make so that files don't overlap, since we can't really accept either because they have other changes than they should (this PR now has aerwhale changes, and the other has the texture change)

**Comment by Azzyypaaras** [comment]
While the effort is certainly to be appreciated, the texture is of too low a quality to be useful here. The leaves look more like cubes than actual leaves, the gold color is somewhat dull, the leaf spacing is awful, tiling is not excellent, quite a lot of issues overall; while it is certain that golden oak leaves could use a fresh coat of paint, I believe you do not currently posses the required experience to retexture them in a manner that keeps consistent with the rest of our textures. I encourage you to continue producing and practicing in pixel art as, in spite of the afforementioned issues I do believe you have potential, and if ever you feel like contributing after having improve please do return.

**Pull request closed without merging**
