### PR TITLE
Include the no chat reports mod with PL

### PR DESCRIPTION
**Pull request by SollyW**

### CODE REVIEW

**Comment by youmukonpaku1337** [comment]
what if a mod depends on no-chat-reports?

**Comment by SollyW** [comment]
Then PL will fulfil it for them. It's JIJ'd

**Review by Azzyypaaras — APPROVED** [review]
This goes hard

**Review by Jack-Papel — APPROVED** [review]

**Comment by Jack-Papel** [comment]
This goes hard. Can I screenshot

**Comment by SollyW** [comment]
This goes hard. You may screenshot

**Comment by Aizistral** [comment]
👍

**Comment by youmukonpaku1337** [comment]
this goes hard. i will screenshot

**Pull request merged**
